name: Grant Repo Permissions For Team

on:
  workflow_dispatch:
   inputs:
    repo-name:
        description: 'Repository Name'
        required: true
    team-slug:
        description: 'Team slug'
        required: true
    permission:
        description: 'permission to be added'
        required: true  
        
env:
  REPO_NAME: "${{ github.event.inputs.repo-name }}"       
  TEAM_SLUG: "${{ github.event.inputs.team-slug }}"
  PERMISSION: "${{ github.event.inputs.permission }}"
  ORG_NAME: "${{ secrets.ORGANIZATION }}"

jobs:
  grant-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Grant Repository Permissions
      run: |
       curl -i -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }" \
       -H "Accept: application/vnd.github.v3+json" \
       -X PUT https://api.github.com/orgs/${{ env.ORG_NAME }}/teams/${{ env.TEAM_SLUG }}/repos/${{ env.ORG_NAME }}/${{ env.REPO_NAME }} -d '{"permission":"admin"}'
#       curl -i -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -X PUT https://api.github.com/orgs/${{ env.ORG_NAME }}/teams/${{ env.TEAM_SLUG }}/repos/${{ env.ORG_NAME }}/${{ env.REPO_NAME }} -d '{"permission":"${{ env.PERMISSION }}"}'
