
name: Assign Users to Repo

on:
  push:
    branches: [ main ]

jobs:
  assign-users:
    runs-on: ubuntu-latest

    steps:
    - name: Assign Users to Repo
      run: |
        USERNAME_LIST="sruthisagar,ALJOEKURIAKOSE,kuriakosemymy"
        for USERNAME in $(echo $USERNAME_LIST | tr ',' ' '); do
            curl -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 -X PUT \
                 "https://api.github.com/repos/Open-FinTech-Test/jokuttan/collaborators/$USERNAME"
        done
