# name: Assign Users to Repository

# on:
#   push:
#     branches: [ main ]

# jobs:
#   assign_users:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Assign Users to Repository
#       uses: peter-evans/repository-dispatch@v1
#       with:
#         repository: Open-FinTech-Test/jokuttan
#         event-type: assign_users
#         client-payload: '{"users": ["sruthisagar", "ALJOEKURIAKOSE", "kuriakosemymy"]}'

# name: Assign Users to Repo

# on:
#   push:
#     branches: [ main ]

# jobs:
#   assign-users:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repo
#       uses: actions/checkout@v2

#     - name: Assign Users to Repo
#       uses: peter-evans/repository-dispatch@v1
#       with:
#         token: ${{ secrets.ORG_ADMIN_TOKEN }}
#         event-type: 'assign-users'
#         client-payload: '{"users": ["sruthisagar", "ALJOEKURIAKOSE", "kuriakosemymy"], "repository": "Open-FinTech-Test/jokuttan"}'



name: Assign Users to Repo

on:
  push:
    branches: [ main ]

jobs:
  assign-users:
    runs-on: ubuntu-latest

    steps:
    - name: Assign Users to Repo
      run: |
        USERNAME_LIST="sruthisagar,ALJOEKURIAKOSE,kuriakosemymy"
        for USERNAME in $(echo $USERNAME_LIST | tr ',' ' '); do
            curl -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 -X PUT \
                 "https://api.github.com/repos/Open-FinTech-Test/jokuttan/collaborators/$USERNAME"
        done
