name: Assign Team to Repo

on:
  workflow_dispatch:
    inputs:
      team-slug:
        description: 'Team slug'
        required: true
      repo-name:
        description: 'Repo name'
        required: true

jobs:
  assign-team:
    runs-on: ubuntu-latest
    steps:
    - name: Assign team to repo
      run: |
        org="${{ secrets.ORGANIZATION }}"
        repo="${{ github.event.inputs.repo-name }}"
        token="${{ secrets.ORG_ADMIN_TOKEN }}"
        
#        team_slug=${{ github.event.inputs.team-slug }}
#        team_id=$(curl -s -H "Authorization: token $token" "https://api.github.com/orgs/$org/teams/$team_slug" | jq -r '.id')
        
        curl -X PUT -H "Authorization: token $token" "https://api.github.com/orgs/$org/teams/$team_slug/repos/$org/$repo"
