name: Update branch protections for another
on:
  push:
    branches:
      - main

jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Update branch protections for another
      env:
        REVIEWER_COUNT: 2
      run: |
        curl -X PUT -H "Authorization: token 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"\
        -H "Accept: application/vnd.github.v3+json"\
        https://api.github.com/repos/Open-FinTech-Test/kukure/contents/RE        
        -d '{"message": "Create README.md", "content": "'"$(echo -n '# My project' | base64)"'", "branch": "main"}'
      
      
