name: Create Repo PUBLIC
on: 
  workflow_dispatch:
    inputs:
      repo-name: 
        description: 'Name of the repository to be created'
        required: true
        default: ''

jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Public Repository
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/${{ secrets.ORGANIZATION }}/repos \
            -d '{"name": "${{ github.event.inputs.repo-name }}", "private": false}'
