name: Create Repo
on: 
  workflow_dispatch:
    inputs:
      repo-name: 
        description: 'Name of the repository to be created'
        required: true
        default: ''

jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Public Repository
        run: |
          gh auth login --with-token <<< ${{ secrets.ORG_ADMIN_TOKEN }}
          gh repo create ${{ github.event.inputs.org-name }}/${{ github.event.inputs.repo-name }} \
          --public
