name: Grant Repo Permissions FOR USER dropdown

on:
  workflow_dispatch:
   inputs:
    repo-name:
        description: 'Repository Name'
        required: true
    user-name:
        description: 'User name'
        required: true
    permission:
        description: 'Select an option'
        required: true
        default: 'push'
        # Use the `choices` parameter to define dropdown list options
        choices: ['push', 'pull', 'admin']  
        
env:
  REPO_NAME: "${{ github.event.inputs.repo-name }}"       
  USER_NAME: "${{ github.event.inputs.user-name }}"
  PERMISSION: "${{ github.event.inputs.permission }}"
  ORG_NAME: "${{ secrets.ORGANIZATION }}"

jobs:
  grant-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Grant Repository Permissions
      run: |
        

        # Make a cURL request to grant the specified permission to the specified user on the specified repository
        curl -i -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" -X PUT -H "Content-Type: application/json" -d '{"permission": "${{ env.PERMISSION }}"}' https://api.github.com/repos/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}/collaborators/${{ env.USER_NAME }}
