name: Protection

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Repository Name'
        required: true

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch protection
        run: |
          curl -X PUT -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" \
            -H "Accept: application/vnd.github.luke-cage-preview+json" \
            -H "Content-Type: application/json" \
            -d '{
              "required_pull_request_reviews": {
                "required_approving_review_count": 2,
                "dismissal_restrictions": {
                  "users": [],
                  "teams": [],
                },
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": true,
                "policies": {
                  "pull_request_reviews": {
                    "required_approving_review_count": 2
                  }
                }
              },
              "enforce_admins": true,
              "required_status_checks": null,
              "required_linear_history": true,
              "allow_force_pushes": false,
              "allow_deletions": false
            }' \
            "https://api.github.com/repos/${{ secrets.ORGANIZATION }}/${{ github.event.inputs.repo_name }}/branches/main/protection"
