name: Create Repo With Readme

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Repository Name'
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create Repository
        run: |
          REPO_NAME="${{ github.event.inputs.repo-name }}"
          ORG_NAME="${{ secrets.ORGANIZATION }}"
          curl -X POST \
            -H "Authorization: token ${{ secrets.ORG_ADMIN_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/$ORG_NAME/repos \
            -d '{"name":"'$REPO_NAME'", "private": false, "auto_init": true, "description": "This is my new repository"}'
