name: LIST USER IN A REPO

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Repo name'
        required: true
        
jobs:
  assign-team:
    runs-on: ubuntu-latest
    steps:
    - name: List users in a repo
      run: |
        org="${{ secrets.ORGANIZATION }}"
        repo="${{ github.event.inputs.repo-name }}"
        token="${{ secrets.ORG_ADMIN_TOKEN }}"
        curl -H "Authorization: token $token" https://api.github.com/repos/$org/$repo/collaborators     
